sudo: false
language: scala
jdk:
- oraclejdk8
before_install:
- nvm install 4.2.6 && nvm use 4.2.6 && npm install
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.sbt/launchers"
  - node_modules
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
- sbt textLintAll textTestAll textBuildHtml test &&
  wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/77904f0859e36d/setup/linux-installer.py
  | python -c "import sys; main=lambda x,y:sys.stderr.write('Download failed\n');
  exec(sys.stdin.read()); main('~/calibre-bin', True)" >/dev/null &&
  export PATH="~/calibre-bin/calibre/:/home/travis/calibre-bin/calibre/:$PATH" &&
  sbt textBuildEpub
after_success:
- "./deploy.sh"
after_script:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
- find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf
env:
  global:
    secure: trVQXloshoD6qC8trtLviRLweSWOCJjq2TRHWuBcJqSJE8x7fJBcWnT2bex++gEPUQV2ee6cdF3/l/WcbPa+yaMDBvC3d4W/1WNXs8VxgI/M8UY5SfvB/nRnFGzxbGBW+AboHvvcvpDRk6jeTr+wQoRAKOIFOX6b3rcQfZh03RFIda9vOcCk48k1SpZKvcI9LHhB2ZA6pMeqk+KkaX8TKScVaOpoHJbnQT/uaMvPb0ZmdV2EKwOg6ZJffy3XPjwazWZWIg6mtPZwbHzVZGLSTnK8vlSqHwmBF49q9+3KjXe/DmBBMnTED+J8TNOv4eUSpmNlxQvBZVUgAVTQpIyQPdFmi6xzSWzS1AzW+ZUVMjTlyBUOzlAdOnqwtihtrvOLc3sGS8otMIBiuM49DWYCICYe/em0IFzsC6zK9okkoOC3Vw9U6Lgs/NvOlCwxpA0GFYpAGlfieqdfYnLVZDk8m0gSF37FcGxHQuRQlOk5f8c/JwvbU+FHBt5OFvGi3VeQ6mqOwPpYWz5Mz30tuKOXgH5RxDv5CLceSd0IsD5oHQEkFkP8m1woq6fUMCIlcv75w/1VVnMHTiTL9UqVnIvXCeEQFRpEZf/BWLe/C4QwrqowRGioZURemEnX4tzq0r9bYvPwIFw7akmDklSxzC2C/9vnpzRDtXJB33b/iGeTzeE=
